language: php

notifications:
  email: false

services:
 - mysql
 
env:
  - DB=mysql

addons:
  mariadb: '10.0'

script: ./systemTest.php
script: ./quizTest.php
before_script:
  - sudo apt-get update
